### PR TITLE
Update to allow 2017 Nvidia Shield models

### PR DESCRIPTION
**Pull request by AndroidUser00110001**
Make using prebuilt kernel
Changes/Clean up of other files
Thanks to Steel01 @ XDA

### CODE REVIEW

**Comment by bigbiff** [comment]
Hi, please push this to https://gerrit.twrp.me for review.

**Comment by AndroidUser00110001** [comment]
I tried at first but couldn't get the gerrit review setup properly for https://gerrit.twrp.me. Any how to guides? I'm sure I research to figure it out...

**Comment by bigbiff** [comment]
You can try this howto: https://forum.xda-developers.com/showthread.php?t=2628545

**Comment by AndroidUser00110001** [comment]
I tried doing that. Getting this error

Is this correct git config --global review.twrp,me.co.username

Upload project device/nvidia/foster/ to remote branch android-6.0:
  branch android-6.0 ( 1 commit, Mon Feb 6 14:23:43 2017 -0500):
         bb2ba498 Thanks to Steel01 @ XDA Add support for 2017 Shield
models Build with prebuilt kernel Update some blobs from updated source
to None (y/N)? y
Traceback (most recent call last):
  File "/home/angelo/OmniROM6/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/angelo/OmniROM6/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/angelo/OmniROM6/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/angelo/OmniROM6/.repo/repo/subcmds/upload.py", line 482, in
Execute
    self._SingleBranch(opt, pending[0][1][0], people)
  File "/home/angelo/OmniROM6/.repo/repo/subcmds/upload.py", line 219, in
_SingleBranch
    self._UploadAndReport(opt, [branch], people)
  File "/home/angelo/OmniROM6/.repo/repo/subcmds/upload.py", line 380, in
_UploadAndReport
    branch.UploadForReview(people, auto_topic=opt.auto_topic,
draft=opt.draft, dest_branch=destination)
  File "/home/angelo/OmniROM6/.repo/repo/project.py", line 184, in
UploadForReview
    dest_branch=dest_branch)
  File "/home/angelo/OmniROM6/.repo/repo/project.py", line 1114, in
UploadForReview
    raise GitError('remote %s has no review url' % branch.remote.name)
error.GitError: remote github has no review url

Thanks for the help. Don't want to be a pain in ass :)

**Comment by bigbiff** [comment]
We use github for authentication

git config --global gerrit.twrp.me.AndroidUser00110001 "AndroidUser00110001"

Visit the site, and make sure to add your public key.

**Comment by AndroidUser00110001** [comment]
Thanks for the help but I cannot get it to work.
I keep getting
"File "/home/angelo/OmniROM6/.repo/repo/project.py", line 1114, in
UploadForReview
    raise GitError('remote %s has no review url' % branch.remote.name)
error.GitError: remote github has no review url"
as the error.
Don't want to be a pain in the ass so I am sure the regular maintainer will
fix it up soon enough.
With TWRP on Shield TV attached to 4K screen there is no output. Is it just
a theme issue or something more?

**Comment by bigbiff** [comment]
For output, I would assume a kernel issue. check dmesg.

For gerrit.twrp.me I usually do the following

git clone git clone ssh://user@gerrit.twrp.me:29418/android_device_nvidia_foster
cd android_device_nvidia_foster
make changes
git remote add gerrit ssh://user@gerrit.twrp.me:29418/android_device_nvidia_foster
git commit -a -m "some message"
git push gerrit HEAD:refs/for/current_branch

**Comment by AndroidUser00110001** [comment]
Thanks for your help! I will try that. If I get it working how do you
prefer the commits? All one commit for all the changes to make TWRP work on
2017 or do it in individual steps for each thing changed?

I used stock kernel so I am not sure if that is the issue. Don't have 4k to
test with. Playing with a theme to see if that gets it to display...

**Comment by bigbiff** [comment]
Up to you, either you can make a squash commit, or just push one at a time.

**Pull request closed without merging**
